Implemented Jpa repositories
Axinalis/simplewebapp pull request #2
Opened 2022-01-03 14:28 UTC by Axinalis

2022-01-03 15:04 UTC, maxzh-gtc requested changes

2022-01-03 15:04 UTC, maxzh-gtc commented on pom.xml
> +						--add-opens=java.base/java.lang=ALL-UNNAMED
Нужен ли тебе этот конфиг? Зачем?

2022-01-03 15:04 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/service/EmployeeService.java
> +    Employee createEmployee( Employee employee);
Пожалуйста, используй дто как параметр и как возвращаемый тип. Сервис возвращает дто, принимает дто, а внутри работает с entity

2022-01-04 09:03 UTC, Axinalis commented on pom.xml
> +						--add-opens=java.base/java.lang=ALL-UNNAMED
Эта конфигурация позволяет мокито получить доступ к рефлексии джавы
Без нее вылетала ошибка о том, что java.lang не может быть предоставлена для безымянного модуля (unnamed module)

2022-01-04 09:03 UTC, Axinalis commented on src/main/java/com/mastery/java/task/service/EmployeeService.java
> +    Employee createEmployee( Employee employee);
Немного не понимаю, с каким entity должен работать класс-сервис?
Мне нужно дополнительно как-то преобразовать Employee в Entity?

2022-01-04 09:03 UTC, Axinalis commented on pom.xml
> +						--add-opens=java.base/java.lang=ALL-UNNAMED
А нет, без него тоже нормально работает

2022-01-04 10:22 UTC, maxzh-gtc requested changes

2022-01-04 10:22 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/service/Mapper.java
> +public class Mapper {
Переименуй класс пожалуйста в EmployeeMapper, т.к имя Mapper очень общее, стоит указать явно для какого он обьекта будет использоваться

2022-01-04 10:22 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/service/Mapper.java
> +public class Mapper {
Для информации: это мог бы быть компонент. Можешь посмотреть на Spring Converter, Spring Conversion Service посмотреть\почитать. Исправлять не нужно. Это для информации.

2022-01-04 10:22 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/service/impl/DefaultEmployeeService.java
> +        Employee employee = repository.saveAndFlush(Mapper.mapToEntity(employeeDto));
стоит ли использовать метод saveAndFlush, можешь ли ты использовать save?

2022-01-04 10:22 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
>          list.add(employee4);
проще один раз в конце написать List.of(employee1, 2,3 ...)

2022-01-04 10:22 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
>      private EmployeeController controller;
Для информации. Тест на контроллер пишется чуть-чуть по-другому. Нужно поднимать контекст и проверять на реальных урлах, а сервис мокать. Можешь посмотреть\почитать для инормациию Пока все ок, тест обновим в следующих заданиях

2022-01-04 10:22 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/service/EmployeeServiceTest.java
> +        when(repository.findAll()).thenReturn(list);
Лучше этот setup делать непоспредсвенно в самом тест методе. Т.е если есть что-то общее для всех тест-кейсов- это в before& setup метод. Если это только нужно для одного теста, то when должен быть там.

2022-01-04 13:30 UTC, maxzh-gtc approved these changes

2022-01-04 13:32 UTC, merged