Added test class for http request
Axinalis/simplewebapp pull request #4
Opened 2022-01-07 09:14 UTC by Axinalis

Added appropriate test for controller.
It still has flaws, like using main database instead of one for testing. But its a start.

2022-01-07 09:43 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/HttpRequestTest.java
> +    public void testAvailability() {
Для информации. Это хороший тест-кейс. Обычно в таких тестах проверяют, что сервис доступен, т.е нужно дернуть какой-нибудь служебный урл типа /managment/ping и посмотреть, что он вернет 200. Но это забегаю чуть вперед. Это из темы про spring boot actuator.

2022-01-07 09:45 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/HttpRequestTest.java
> +    public void testCreateUpdateDelete(){
Тесты на create\delete\update должны быть разделены по отдельным методам.

2022-01-07 09:52 UTC, maxzh-gtc requested changes
Твой тест является integrationTest по-сути, т.к он проверяет работы не только конроллера, а фактически проходит через все приложение и достаяет данные из БД (обычно это H2 база, но можно и реальную БД для тестового проекта). Обычно такие тесты пишут в таком формате, например на get call:
Given employee in the DB (т.е создаем и ложим емлоии в БД, напрямую в БД)
When делаем рест колл на наш урл
Then проверяем что вернулся наш employee из БД в виде ожидаемого json

2022-01-07 09:56 UTC, maxzh-gtc commented
Я оставил тебе коменты в пул-реквесте номер 3. В этом пул-реквест мы все покроем тестами. Свой тест текущий тест можешь оставить. Напишем unit-test на контроллер с использование MockMvc. Есть ресурс Baeldung в интернете, там можно посмотреть примеры, ну и другие конечно. В рамках этого теста следует проверить, что наш контроллер возвращает ожидаемы значения на get\update\delete\create (это все отдельные тест кейсы) + проверить, что наша bean validation работает.

2022-01-10 15:28 UTC, maxzh-gtc requested changes
Верное направление и уже лучше. Тесты для create\update\delete написаны неплохо. Но тест нужно переделать. Тебе нужно поднять спринг тест контектс, для того, чтобы иметь возможно проверить bean validation.  Можно использовать аннотации ниже.
1. Почитать про ExtendWith. Что за аннотация? Чем отличается @ExtendWith(MockitoExtension.class) от @ExtendWith(SpringExtension.class)
2.  Почитать и разобратьс с @WebMvcTest.
3. Разница аннотаций mock & mockBean
4. Добавь несколько проверок для beanValidation. Если затрудняешься, можешь написать мне в телегу тестовые сценарии для этих кейсов.

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/HttpRequestTest.java
> +//Not working yet
Для игнора тестов есть специальная аннотация. Ее можно тут использовать. Например, если тест недописан итд

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    public void getListsWithAndWithoutNames() throws Exception {
Это должны быть раздельные сценарии. Т.к ты делаешь два кола к контроллеру

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private String mapToJson(Object object){
Сначала идут все public методы, потом private. Т.е они будут в самом низу файла

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        String firstName = list.get(forNameSearch).getFirstName();
Почему явно не написать то имя, которое ты хочешь? String firstName = "Anton"?

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        when(service.employeeList(params)).thenReturn(Arrays.asList(list.get(forNameSearch)));
Arrays.asList(list.get тебе не кажется это странным :)?

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    public void testSpecificEmployees() throws Exception {
В чем идея теста? в одном случае ты ожидаешь  200, в другом 404? Методом исключения, я так понимаю, что это был должен тест, shouldReturn404WhenEmployeeIsNotFound.

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        EmployeeDto returnedEmployee = mapFromJson(result.getResponse().getContentAsString(), new TypeReference<EmployeeDto>() {});
Лучше не перегонять обратно в дто, а сравнивать саму строку. Либо через MockMvcResultMatchers либо просто как строки. Обнови пожалуйта для тестов update\create

2022-01-10 15:28 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        verify(service, times(1)).deleteEmployee(id);
По умолчанию verify(service)........=verify(service, times(1)). Если нужно > 1, тогда ее используют

2022-01-11 13:34 UTC, Axinalis commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        String firstName = list.get(forNameSearch).getFirstName();
Не хочу завязывать код на тех строках, которые могут быть легко изменены

2022-01-11 21:13 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private EmployeeRepository repository;
Тебе не нужно создавать мок репозитория. Ты тестируешь контроллер. В контроллер есть одна зависимость для внедрения, только ее достаточно замокать

2022-01-11 21:14 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        String firstName = list.get(forNameSearch).getFirstName();
Что ты имешь ввиду? Кто их будет менять? Это же тест, а не код приложения. Ты контроллируешь входные\выходные данные для него. Ты можешь прям здесь создать список из 1\2 пользователей, а не создавать общий список  и как-то его шарить между тестами

2022-01-12 07:06 UTC, Axinalis commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private EmployeeRepository repository;
Дело в том, что без этого мока спринг пытался инициализировать employeeRepository
Даже несмотря на то, что там WebMvcTest не должен инициализировать репозиторий (и да, я добавлял аннотацию @Repository, но и с ней он не работал)

2022-01-12 21:15 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private EmployeeRepository repository;
@ExtendWith(SpringExtension.class)
@WebMvcTest(EmployeeController.class)
public class EmployeeControllerTests {
    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private ObjectMapper objectMapper;
    @MockBean
    private IEmployeeService employeeService;
    
    Попробуй такой конфиг

2022-01-14 12:56 UTC, Axinalis commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private EmployeeRepository repository;
![image](https://user-images.githubusercontent.com/45764881/149518767-a1cc84fc-a042-41cc-83bf-f6d7c1c0948f.png)
Все то же самое
Если же добавить @mockbean repository, то все работает

2022-01-24 14:52 UTC, maxzh-gtc approved these changes
Ок, спасибо за апдейты. В целом все ок, можно мержить. Но сначала плиз поправь мелкие недочеты и можешь сам мержить без меня

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        when(service.employeeList(new HashMap<>())).thenReturn(Arrays.asList(newEmployeeDto(false)));
если у тебя j11 можешь использовать List.of

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private EmployeeDto newEmployeeDto(boolean valid){
лучше назвать глаголом create\build EmpoleeDto. Я бы создал два метода createEmployeeDto, createInvalidEmployeeDto

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +        String parameters = String.format("?firstName=%s&secondName=%s", firstName, secondName);
Урл мог бы быть сразу таким /employee?firstName=%s&secondName=%s

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +                .andExpect(jsonPath("status").value("404 NOT_FOUND"));
Для информации. Можно проверить все поля, которые используются у тебя в соотв. методе cotrollerAdvice

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +                .andExpect(jsonPath("$.details.firstName").isNotEmpty())
Есть ли возможность здесь проверить явный текст ошибки?

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    public void testCreateEmployeeWithNullFields() throws Exception {
Чем этот метод отличается от testCreateValidation?

2022-01-24 14:52 UTC, maxzh-gtc commented on src/test/java/com/mastery/java/task/rest/EmployeeControllerTest.java
> +    private String mapToJson(Object object){
Для информации. Ты можешь сразу в тестах использовать mapper.writeValueAsString(object) и использовать throws в сигнатуре.

2022-01-25 10:04 UTC, merged