Feature logging actuator and swagger
Axinalis/simplewebapp pull request #5
Opened 2022-01-14 12:38 UTC by Axinalis

2022-01-17 10:08 UTC, maxzh-gtc requested changes

2022-01-17 10:08 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/exceptions/ErrorHandlingAdvice.java
> +    public ExceptionMessage handlePathVariableException(MethodArgumentTypeMismatchException exception){
Для информации. В принципе можно было б объединить все случаи для 400 в один хэндлер. Типы экспешенов можно через запятую перечислить

2022-01-17 10:08 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
> +        log.info("Employee controller has been instantiated");
Логировать имеет смысл то, что отвечает за работу приложения, чтобы потом по логам можно было отследить путь запроса, понять, где возникла runtime ошибка итд. Лог в конструктуре может быть полезен только для разработки\дебага, его нужно удалить

2022-01-17 10:08 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/exceptions/ErrorHandlingAdvice.java
>      public ExceptionMessage handleValidationException(MethodArgumentNotValidException exception){
Нужно добавить логирование для всех ошибок

2022-01-17 10:08 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
> +    private Logger log;
обычно логер делают статическим полем и сразу инициализируют

2022-01-17 10:08 UTC, maxzh-gtc commented on src/main/resources/log4j2.xml
> +        <Logger name="com.mastery.java.task.rest.EmployeeController" level="info">
Пакет нужно будет поменять для всех классов твоего приложения.

2022-01-19 07:52 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/exceptions/ErrorHandlingAdvice.java
> +        log.error("Error in parsing path variable: {} {}", exception.getName(), exception.getMessage());
логируй пожалуйста сам экспшн пожалуйста

2022-01-24 15:07 UTC, maxzh-gtc requested changes

2022-01-24 15:07 UTC, maxzh-gtc commented on pom.xml
> +		<dependency>
Для чего понадобилась эта зависимость?

2022-01-24 15:07 UTC, maxzh-gtc commented on pom.xml
> +			<plugin>
Для чего потребовалась конфигурация планигов?

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/MainApp.java
> +                "1.0",
Что будет происходит, если измениться версия приложения?
Я бы предложил тебе "протягивать" description,version,title из pom через application.properties.
Также используй builder для создания new ApiInfoBuilder(). 
Как теоретический материал еще почитай про шаблон проектирования билдер.

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/MainApp.java
> +    private ApiInfo apiInformation(){
Сначало идут public методы класса, затем private. Этот метод должен быть после swaggerResourcesProvider

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/MainApp.java
> +    @Primary
Обязательно ли primary?

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/exceptions/ErrorHandlingAdvice.java
> +    private static Logger log = LogManager.getLogger("com.mastery.java.task");
зачем указывать пакет здесь? обычно здесь указывают класс ErrorHandlingAdvice.class

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/exceptions/ErrorHandlingAdvice.java
> +        log.warn("Employee wasn't found with message: {}", exception.getStackTrace().toString());
Общий комент
>exception.getStackTrace().toString()
Указывай просто excepiton. В логерах должен быть метод, который принимает Exception.class как параметр и знает как с ним работать.

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
> +    private static Logger log = LogManager.getLogger("com.mastery.java.task");
аналогичный комент. Используй класс EmployeeController вместо пакета

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
> +        log.info("Request for list of employees came");
здесь было бы полезно добавить params, т.к это информация даст нам больше сведений, а пустой лог, не даст

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
> +        log.info("Request to create new employee came");
Здесь тоже лучше залогировать входящий employee

2022-01-24 15:07 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/rest/EmployeeController.java
>      @PostMapping()
Обязательно ли писать PostMapping со скобочками? Это можно убрать

2022-01-27 09:34 UTC, Axinalis commented on pom.xml
> +			<plugin>
Это было необходимо для докера
Там есть пару тестов, которые не проходятся пока что нормально, поэтому я их решил проигнорировать. Хотел проверить работоспособность приложения в докере

2022-01-27 09:36 UTC, Axinalis commented on src/main/java/com/mastery/java/task/MainApp.java
> +                "1.0",
Про шаблон знаю, а вот по "протягиванию" различных характеристик, честно говоря, пока не все хорошо
Ни один из нужных способов не работает

2022-01-27 09:36 UTC, Axinalis commented on src/main/java/com/mastery/java/task/MainApp.java
> +    @Primary
Да, там несколько таких бинов

2022-01-27 10:34 UTC, Axinalis commented on pom.xml
> +		<dependency>
Возникала ошибка без нее

2022-01-30 18:31 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/MainApp.java
> +    @Value("${app.version}")
Сфагер конфиг должен быть в конфиг классе. Не заметил сразу, что это в spring boot классе.

2022-01-30 18:37 UTC, maxzh-gtc approved these changes
Перенеси только свагер конфиг в другой класс.

2022-01-31 10:18 UTC, merged