Added activemq suppport
Axinalis/simplewebapp pull request #6
Opened 2022-01-31 12:13 UTC by Axinalis

2022-02-01 21:47 UTC, maxzh-gtc requested changes

2022-02-01 21:47 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/MainApp.java
> +    @Value("${active-mq.broker-url}")
Ты пишешь конфигурацию, верно. Конфигурация должна находиться в соотсветвующем классе. Также, как в случае со свагером. Пожалуйста перенеси в @Configuration класс

2022-02-01 21:47 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/jms/JmsConsumer.java
> +            log.info("Mapping received object to EmployeeDto class");
Здесь уместнее написать Employee message consumed from Queue

2022-02-01 21:47 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/jms/JmsConsumer.java
> +        log.info("Employee's name is {}", employee.getFirstName());
У тебя есть бин-валидация, которую ты можешь переиспользовать для проверки валидности

2022-02-01 21:47 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/jms/JmsConsumer.java
> +public class JmsConsumer implements MessageListener {
Также на этот класс нужно написать юнит-тест.

2022-02-05 12:55 UTC, maxzh-gtc commented on src/main/java/com/mastery/java/task/jms/JmsConsumer.java
> +            if(employee.getEmployeeId() == null){
т.к выше есть проверка на валидация, эта проверка уже избыточна

2022-02-05 12:55 UTC, maxzh-gtc approved these changes

2022-02-06 14:46 UTC, Axinalis commented on src/main/java/com/mastery/java/task/jms/JmsConsumer.java
> +            if(employee.getEmployeeId() == null){
Это проверка на то, создается или изменяется информация о работнике
Если айди не указан, значит мы создаем нового
Если указан, то изменяем существующего (или выкидываем исключение, что такого нет)

2022-02-06 14:52 UTC, merged